var data = [
  {
    name: 'The Chariot',
    bio: 'I like food.',
    phone: '123-123-4567',
    avatar: 'http://highlightmagazine.net/wp-content/uploads/2012/08/The-Chariot-One-Wing-2012.jpeg',
  },
  {
    name: 'The Number 12 Looks Like You',
    bio: 'kasjkdhfjkashdjfk dhfkjashdkjfhaskjdfhkajshdfkjl asdljfhak sljdhfk jlashdjk askjfhalkjsdhflkjas',
    phone: '123-123-4567',
    avatar: 'http://www.metal411.com/wp-content/uploads/2013/11/The-Number-Twelve-Looks-Like-You.jpg',
  },
  {
    name: 'Between the Buried and Me',
    bio: 'lahsdkjlfhajksdhfkjashdkjf haskjdfhkajshdfkjl asdljfhaksljdhf kjlashdjk askjfhalkjsdhflkjas',
    phone: '123-123-4567',
    avatar: 'http://2.bp.blogspot.com/-hyHfZo9QlFU/UARkx1UkwnI/AAAAAAAANzI/8lkzvA_6Vl0/s400/Horns%2BUp%2BRocks%2BBetween%2BThe%2BBuried%2BAnd%2BMe%2BThe%2BParallax%2BII%2BFuture%2BSequence%2BAlbum%2BCover%2BArt',
  },
  {
    name: 'Bring Me The Horizon',
    bio: 'lahsdkjlfhajksdhfkjashdkjf haskjdfhkajshdfkjl asdljfhaksljdhf kjlashdjk askjfhalkjsdhflkjas',
    phone: '123-123-4567',
    avatar: 'http://1.bp.blogspot.com/-xbgRAUnUu-c/US4vebpVCsI/AAAAAAAAARc/Ku5FCTygQyM/s1600/Sempiternal.jpg',
  },
  {
    name: 'We Came As Romans',
    bio: 'lahsdkjlfhajksdhfkjashdkjf haskjdfhkajshdfkjl asdljfhaksljdhf kjlashdjk askjfhalkjsdhflkjas',
    phone: '123-123-4567',
    avatar: 'http://wac.450f.edgecastcdn.net/80450F/noisecreep.com/files/2011/07/wcar-476-71511.jpg',
  },
  {
    name: 'Of Mice and Men',
    bio: 'lahsdkjlfhajksdhfkjashdkjf haskjdfhkajshdfkjl asdljfhaksljdhf kjlashdjk askjfhalkjsdhflkjas',
    phone: '123-123-4567',
    avatar: 'http://upload.wikimedia.org/wikipedia/en/9/97/Of_Mice_and_Men_album_cover.jpg',
  },
  {
    name: 'As I Lay Dying',
    bio: 'lahsdkjlfhajksdhfkjashdkjf haskjdfhkajshdfkjl asdljfhaksljdhf kjlashdjk askjfhalkjsdhflkjas',
    phone: '123-123-4567',
    avatar: 'http://upload.wikimedia.org/wikipedia/en/d/d8/Shadows_are_security.jpg',
  },
  {
    name: 'Converge',
    bio: 'lahsdkjlfhajksdhfkjashdkjf haskjdfhkajshdfkjl asdljfhaksljdhf kjlashdjk askjfhalkjsdhflkjas',
    phone: '123-123-4567',
    avatar: 'http://upload.wikimedia.org/wikipedia/en/b/b5/Converge-JaneDoe.jpg',
  },
  {
    name: 'For Today',
    bio: 'lahsdkjlfhajksdhfkjashdkjf haskjdfhkajshdfkjl asdljfhaksljdhf kjlashdjk askjfhalkjsdhflkjas',
    phone: '123-123-4567',
    avatar: 'http://mindequalsblown.net/wp-content/uploads/2010/08/For-Today-Breaker.jpg',
  },
  {
    name: 'Norma Jean',
    bio: 'lahsdkjlfhajksdhfkjashdkjf haskjdfhkajshdfkjl asdljfhaksljdhf kjlashdjk askjfhalkjsdhflkjas',
    phone: '123-123-4567',
    avatar: 'http://www.metalkingdom.net/album/cover/d92/56965_norma_jean_redeemer.jpg',
  },
  {
    name: 'August Burns Red',
    bio: 'lahsdkjlfhajksdhfkjashdkjf haskjdfhkajshdfkjl asdljfhaksljdhf kjlashdjk askjfhalkjsdhflkjas',
    phone: '123-123-4567',
    avatar: 'http://ecx.images-amazon.com/images/I/61HnQtPGTtL.jpg',
  },
  {
    name: 'A Day To Remember',
    bio: 'lahsdkjlfhajksdhfkjashdkjf haskjdfhkajshdfkjl asdljfhaksljdhf kjlashdjk askjfhalkjsdhflkjas',
    phone: '123-123-4567',
    avatar: 'http://www.examiner.com/images/blog/EXID25851/images/a-day-to-remember-homesick(2).jpg',
  },
  {
    name: 'In Flames',
    bio: 'lahsdkjlfhajksdhfkjashdkjf haskjdfhkajshdfkjl asdljfhaksljdhf kjlashdjk askjfhalkjsdhflkjas',
    phone: '123-123-4567',
    avatar: 'http://tracksix.files.wordpress.com/2008/02/purposecoverlores.jpg',
  },
  {
    name: 'Eluveite',
    bio: 'lahsdkjlfhajksdhfkjashdkjf haskjdfhkajshdfkjl asdljfhaksljdhf kjlashdjk askjfhalkjsdhflkjas',
    phone: '123-123-4567',
    avatar: 'http://www.stereokiller.com/newsreviews/newsimage/helvetios.jpg',
  },
  {
    name: 'As Blood Runs Black',
    bio: 'lahsdkjlfhajksdhfkjashdkjf haskjdfhkajshdfkjl asdljfhaksljdhf kjlashdjk askjfhalkjsdhflkjas',
    phone: '123-123-4567',
    avatar: 'http://userserve-ak.last.fm/serve/_/58709115/Demo%2BCover.jpg',
  },{
    name: 'Black Dahlia Murder',
    bio: 'lahsdkjlfhajksdhfkjashdkjf haskjdfhkajshdfkjl asdljfhaksljdhf kjlashdjk askjfhalkjsdhflkjas',
    phone: '123-123-4567',
    avatar: 'http://upload.wikimedia.org/wikipedia/en/6/66/MiasmaAlbumCover.jpg',
  },
  {
    name: 'The Architects',
    bio: 'lahsdkjlfhajksdhfkjashdkjf haskjdfhkajshdfkjl asdljfhaksljdhf kjlashdjk askjfhalkjsdhflkjas',
    phone: '123-123-4567',
    avatar: 'http://newnoisemagazine.com/wp-content/uploads/2014/01/Architects-UK-Lost-Forever-Lost-Together-cover.jpg',
  },
  {
    name: 'Memphis May Fire',
    bio: 'lahsdkjlfhajksdhfkjashdkjf haskjdfhkajshdfkjl asdljfhaksljdhf kjlashdjk askjfhalkjsdhflkjas',
    phone: '123-123-4567',
    avatar: 'http://popcultureblog.dallasnews.com/files/2012/07/image002.jpg',
  },
  {
    name: 'Dillinger Escape Plan',
    bio: 'lahsdkjlfhajksdhfkjashdkjf haskjdfhkajshdfkjl asdljfhaksljdhf kjlashdjk askjfhalkjsdhflkjas',
    phone: '123-123-4567',
    avatar: 'http://mmminimal.wpengine.netdna-cdn.com/wp-content/uploads/2011/03/Dillinger_Escape_Plan_ire-works.jpg',
  },
  {
    name: 'Suicide Silence',
    bio: 'lahsdkjlfhajksdhfkjashdkjf haskjdfhkajshdfkjl asdljfhaksljdhf kjlashdjk askjfhalkjsdhflkjas',
    phone: '123-123-4567',
    avatar: 'http://upload.wikimedia.org/wikipedia/en/0/01/Suicide_Silence_-_The_Cleansing.jpg',
  },
  {
    name: 'All That Remains',
    bio: 'lahsdkjlfhajksdhfkjashdkjf haskjdfhkajshdfkjl asdljfhaksljdhf kjlashdjk askjfhalkjsdhflkjas',
    phone: '123-123-4567',
    avatar: 'http://www.nuffradio.com/web/pictures/az_791_Overcome_All%20That%20Remains.jpg',
  },{
    name: 'UnderOath',
    bio: 'lahsdkjlfhajksdhfkjashdkjf haskjdfhkajshdfkjl asdljfhaksljdhf kjlashdjk askjfhalkjsdhflkjas',
    phone: '123-123-4567',
    avatar: 'http://vadimages.files.wordpress.com/2009/05/album-define-the-great-line-cd-dvd.jpg',
  },
  {
    name: 'Oh, Sleeper',
    bio: 'lahsdkjlfhajksdhfkjashdkjf haskjdfhkajshdfkjl asdljfhaksljdhf kjlashdjk askjfhalkjsdhflkjas',
    phone: '123-123-4567',
    avatar: 'http://i708.photobucket.com/albums/ww90/elihu_core/oslws.jpg',
  },
  {
    name: 'Parkway Drive',
    bio: 'lahsdkjlfhajksdhfkjashdkjf haskjdfhkajshdfkjl asdljfhaksljdhf kjlashdjk askjfhalkjsdhflkjas',
    phone: '123-123-4567',
    avatar: 'http://ecx.images-amazon.com/images/I/61yC5IEUsDL.jpg',
  },
  {
    name: 'Poison the Well',
    bio: 'lahsdkjlfhajksdhfkjashdkjf haskjdfhkajshdfkjl asdljfhaksljdhf kjlashdjk askjfhalkjsdhflkjas',
    phone: '123-123-4567',
    avatar: 'http://www.punknews.org/images/interviews/int-1353953595.jpg',
  },
  {
    name: 'War of Ages',
    bio: 'lahsdkjlfhajksdhfkjashdkjf haskjdfhkajshdfkjl asdljfhaksljdhf kjlashdjk askjfhalkjsdhflkjas',
    phone: '123-123-4567',
    avatar: 'http://www.metalkingdom.net/album/cover/d77/21955_war_of_ages_pride_of_the_wicked.jpg',
  },
  {
    name: 'Between the Buried and Me',
    bio: 'lahsdkjlfhajksdhfkjashdkjf haskjdfhkajshdfkjl asdljfhaksljdhf kjlashdjk askjfhalkjsdhflkjas',
    phone: '123-123-4567',
    avatar: 'http://2.bp.blogspot.com/-hyHfZo9QlFU/UARkx1UkwnI/AAAAAAAANzI/8lkzvA_6Vl0/s400/Horns%2BUp%2BRocks%2BBetween%2BThe%2BBuried%2BAnd%2BMe%2BThe%2BParallax%2BII%2BFuture%2BSequence%2BAlbum%2BCover%2BArt',
  },
]